
projects:
- {name: Languages, folder: 'proj-1'}
- {name: Graphical Software, folder: 'proj-2'}
- {name: Operating Systems, folder: 'proj-3'}
- {name: Application Software, folder: 'proj-4'}



experience:

- {position: 'some shit',
  date: 'Date: Jan/2016 - April/2016',
  location: 'Connected Labs',
  quote: '<p>I tested a variety of different software applications and hardware devices using multiple platforms including iOS, tvOS, Android and Web. In addition, I wrote test scripts using Selenium Web driver and Calabash Android in order to automate web and app testing in adherence to client demands. Through the use of Swagger’s framework, I gained experience in API testing for web applications. Similarly, I built upon my background in Pivotal Tracker and Bugzilla.</p>',
  logo: 'logo1.png'}
- {position: 'Quality Assurance Manager',
  date: 'Date: March/2015 - Aug/2015',
  location: 'Obero Solutions',
  quote: '<p>Over the course of a term, I created Obero Solutions web application testing system. Each new application was tested for bugs and reviewed to ensure compliance to client needs after each sprint. Alongside this project, I developed Obero Solutions Business Requirement and Build Release documents for their Incentive Compensation Management web application while working closely with our clientele and the primary development team.</p>',
  logo: 'logo6.png'}
- {position: 'iOS Game Development',
  date: 'Date: Jan/2016 - Present',
  location: 'Personal Project',
  quote: '<p> I used obj-c to create a reaction based game involving UIGestureRecognizers, SpriteKit Particle Emitters and Facebooks POP Animation Engine. Please check it out on my github page! </p>',
  logo: 'logo4.png'}
- {position: 'Math and English Tutor',
  date: 'Date: Nov./2011 - May/2013',
  location: 'Learna',
  quote: '<p>I tutored children from ages 5-12 in both Math and English, which provided me the opportunity to work alongside teachers from which I gained valuable leadership and communications skills. </p>',
  logo: 'logo3.png'}
- {position: 'Mentorship Developer',
  date: 'Date: Feb./2011 – Sept./2011',
  location: 'Turner Fenton SS',
  quote: '<p>I helped smooth the transition into high school and the IBMYP (International Baccalaureate) program for incoming freshmen. I introduced important concepts of the program to the group that I was given responsibility over. </p>',
  logo: 'logo5.png'}
- {position: 'Course Work',
  date: 'Date: Sept/2014 - Present',
  location: 'University of Waterloo',
  quote: '<p>• <strong> Algorithms and Data Structures: </strong> Learned various efficient sorting and graphing algorithms along with multiple data structures 
  <br>• <strong>Engineering Design with Embedded Systems:</strong> Studied SDLC and Android (java) development <br>
  • <strong>Digital Circuits and Systems:</strong> Experience with Altera FPGAs, along with state machines and VHDL programming </p>',
  logo: 'logo2.png'}
  




